AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
    GitReport:
        Type: AWS::Serverless::Function
        Properties:
            Handler: lambda_function.lambda_handler
            Runtime: python3.12
           # CodeUri: .aws-sam.GitReport
            MemorySize: 512
            Timeout: 60
            Policies:
                - AWSLambdaBasicExecutionRole
                - SecretsManagerReadWrite
            Events:
                ScheduledEvent:
                    Type: Schedule
                    Properties:
                        Schedule: cron(0 0 1 * ? *)
